import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  SecondaryContainer: {
    width: "100%",
    height: "100%",
    backgroundColor: "black",
    borderRadius: 5,
    alignItems: "center",
    justifyContent: "center",
    alignContent: "center",
  },
  img: {
    width: 200,
    height: 200,
    borderRadius: 100,
  },
  text: {
    fontSize: 25,
    color: "white",
    fontWeight: "bold",
    marginTop: 15,
  },
  inputs1: {
    width: "90%",
    height: "13%",
    backgroundColor: "white",
    borderRadius: 5,
    alignSelf: "center",
    margin: 5,
    fontSize: 20,
  },
  containerinputs: {
    width: "100%",
    height: 300,
    marginTop: 75,
  },
  textoinputs: {
    color: "white",
    fontSize: 20,
    marginTop: 20,
    marginLeft: 30,
    marginTop: 15,
    fontWeight: "bold",
  },
  botcaucular: {
    width: "90%",
    height: "15%",
    backgroundColor: "red",
    justifyContent: "center",
    alignSelf: "center",
    marginTop: 15,
    borderRadius: 5,
  },
  textobot: {
    color: "white",
    fontSize: 30,
    textAlign: "center",
    fontWeight: "bold",
  },
  SecondaryContainer2: {
    width: "100%",
    height: "100%",
    backgroundColor: "black",
    borderRadius: 5,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    marginTop: 50,
  },
  textfrase: {
    color: "green",
    fontWeight: "bold",
    fontSize: 30,
    marginTop: 15,
  },
  textoprecos: {
    color: "white",
    fontSize: 20,
  },
});
